version: "3.9"

name: brave-browser
services:
  brave-browser:
    image: rshmyrev/brave-browser
    build: .
    hostname: debian
    environment:
      - DISPLAY=unix$DISPLAY # X11
      - PULSE_SERVER=unix:$XDG_RUNTIME_DIR/pulse/native # PulseAudio
    devices:
      - /dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro # X11
      - $XDG_RUNTIME_DIR/pulse:$XDG_RUNTIME_DIR/pulse:ro # PulseAudio
      - /run/dbus:/run/dbus:ro # D-Bus
      - home:/home/user
      - $HOME/Downloads:/home/user/Downloads
    shm_size: 1GB
    cap_drop: [ ALL ]

volumes:
  home:
