# Remove the version key

services:
  brave-browser:

    image: ${MY_IP}:5000/docker-dev-python3
    environment:
      - DISPLAY=unix$DISPLAY # X11
      - PULSE_SERVER=unix:$XDG_RUNTIME_DIR/pulse/native # PulseAudio
    devices:
      - /dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro # X11
      - $XDG_RUNTIME_DIR/pulse:$XDG_RUNTIME_DIR/pulse:ro # PulseAudio
      - /run/dbus:/run/dbus:ro # D-Bus
      #- $HOME/Downloads:/tmp/user/Downloads
    shm_size: 1GB
    cap_drop: [ALL]

#volumes:
 #home:
